### ISSUE TITLE
Quarter Plan - 2016/Q2

### ISSUE THREAD

**Issue by DotJoshJohnson** [TrueCommerce/Roadmap#1]
## Urgent Items
*Must be completed and released before touching any other task (i.e. NOW).*
- **None**

## Roadmap Items
*"Normal" roadmap tasks and other planned items.*
* **TrueCommerce Toolbox (VS Code Extension)**
  - [x] Implement all "alpha" features (TrueCommerce/vscode-x12#1)
  - [x] Add token discovery tooltips (TrueCommerce/vscode-x12#2)
  - **BSP Parsing and Data Review**
    - [x] Define VS Code Extension Scope (internal/external, naming, etc)
    - [x] IMT Connectivity (TrueCommerce/vscode-tctoolbox#25)
    - Data Parsing
      - ~~Fixed-Position (TrueCommerce/vscode-tctoolbox#18)~~ (see notes)
      - ~~Delimited (TrueCommerce/vscode-tctoolbox#19)~~ (see notes)
      - ~~XML/Framework (TrueCommerce/vscode-tctoolbox#20)~~ (see notes)
  - **BSP/EPP Integration**
    - ~~Token Tooltips (TrueCommerce/vscode-tctoolbox#22)~~ (see notes)
    - [x] Report unmapped required elements (TrueCommerce/vscode-tctoolbox#21)
  - Updates per feedback (ongoing)
    - [x] ISA/GS Editor Functionality
    - [x] Multi-File manipulation/updating (Folder)
    - [x] Missing Loop Flag
    - [x] Element position flag in tooltip
    - [x] Extension Buttons Not Appearing (TrueCommerce/vscode-tctoolbox#28)
    - [x] ISA/GS Editor Silently Ignores Certain Files (TrueCommerce/vscode-tctoolbox#29)

* **TrueCommerce Sandbox**
  - [x] Deploy New API Server
  - [x] Deploy profile update web-tool (http://sandboxtool.tcpsg.net/)
  - Scope Profile Sync
    - [x] Initial scope meeting (5/16)

* **XML Tools (VS Code Extension)**
  - [x] Fix line break minification issue (TrueCommerce/vscode-xml#54)
  - [x] Add formatting support for XSLT files (TrueCommerce/vscode-xml#55)

* **Timecard Service**
  - [x] Upgrade to ASP.NET 5 (TrueCommerce/TimecardService#4)
  - [x] Upgrade to Angular 2.0 (TrueCommerce/TimecardService#3)
  - [x] Data Migration Tool (TrueCommerce/TimecardService#7)
  - [x] Potential UI Updates (TrueCommerce/TimecardService#8 & TrueCommerce/TimecardService#9)
  - [x] Report 1 - Roll-Up Utilization Report (TrueCommerce/TimecardService#10)
  - ~~Report 2 (TBD)~~
  - ~~Report 3 (TBD)~~
  - ~~Report 4 (TBD)~~

* TIER3 Reserve @ 25% (ongoing)

## Debt Items
*Technical debt. The kind that makes you cry in the night.*
- [x] **PsgServices:** Move Database Access Layer (TrueCommerce/PsgServices#6)
- ~~**XML Tools:** Move storage.json Logic to New Service (TrueCommerce/vscode-xml#50)~~

## Meeting Notes
*Any noteworthy items from the monthly stakeholder meeting (that aren't action items) can go here.*
* As of 5/13, there are 34-56 points open for the month of May (out of about 100 allowed for the month). 8-13 of these points are Nexus-related (TIER III).

* Due to increasing Tier III demands and the required platform changes for the BSP integration, I am proposing we move the flat file parsing stories to the next quarter. This will ensure I can deliver a solid build with the priority BSP features before adding the "nice-to-haves".
